1. enter name github with name
git congif -- global user.name "name"
2. enter email github with email
git config -- global user.email "namemail"
3.clone .git
git clone htt://"thead"
4.git add .
5. git commit -m "first commit"
6. git push
7. test
8.ahihi
9.lammn
10.123
11.223
12.fff
13.loloo
14.jjjj
15.kikk
16.kkkkp
17.kiik
18.kdKEK
19.rkrrii